services:
  app:
    build:
      context: ./
    container_name: playlisttransferapi_app
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    networks:
      global_network:
      default:
    volumes:
      - app_localstorage:/app/storage
      - ./logs/fastapi:/app/logs

  db:
    image: postgres:latest
    container_name: playlisttransferapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./etc/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./logs/postgresql:/var/log/postgresql:z
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      default:

networks:
  global_network:
    external: true

volumes:
  postgres_data:
  app_localstorage:
