"""init

Revision ID: 0087e441db64
Revises: 
Create Date: 2025-05-28 16:59:47.561916

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0087e441db64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_tokens',
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('app_bundle', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('token_data', sa.String(), nullable=False),
                    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('source_tokens_pkey'))
                    )
    op.create_index(op.f('source_tokens_id_idx'), 'source_tokens', ['id'], unique=False)
    op.create_table('transfers',
                    sa.Column('from_source', sa.String(), nullable=False),
                    sa.Column('to_source', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=False),
                    sa.Column('app_bundle', sa.String(), nullable=False),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('transfers_pkey'))
                    )
    op.create_index(op.f('transfers_id_idx'), 'transfers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('transfers_id_idx'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('source_tokens_id_idx'), table_name='source_tokens')
    op.drop_table('source_tokens')
    # ### end Alembic commands ###
